apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-2
  labels:
    app: helloWorld
    rel: stable
spec:
  replicas: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: hello-world-2
  template:
    metadata:
      labels:
        app: hello-world-2
    spec:
      containers:
        - name: hello-world-container
          image: k8.test/hello-world:v6
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 5