apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: helloWorld
    rel: stable
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
  - name: http
    port: 8080
    targetPort: 8080