apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: helloWorld
    rel: stable
spec:
  volumes:
    - name: persistent-claim
      persistentVolumeClaim:
        claimName: claim-5m
    - name: html
      emptyDir: {}
    - name: props
      hostPath:
        path: /home/sotirisalfonsos/IdeaProjects/ckad-material/src/main/resources/application.properties
        type: File
    - name: docker
      hostPath:
        path: /var/run/docker.sock
        type: Socket
  containers:
    - name: docker
      image: docker
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
    - name: hello-world-container
      image: k8.test/hello-world:v7
      imagePullPolicy: Never
      volumeMounts:
        - name: persistent-claim
          mountPath: /data/storage
        - name: props
          mountPath: /config/application.properties
          readOnly: true
        - name: html
          mountPath: /usr/share
          readOnly: true
        - name: docker
          mountPath: /var/run/docker.sock
      readinessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 5
      ports:
        - containerPort: 8080
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx
          readOnly: true
      resources:
    - name: html-updater
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - while true; do date >> /data/storage/index.html;sleep 10; done
      resources:
      volumeMounts:
        - name: persistent-claim
          mountPath: /data/storage
        - name: html
          mountPath: /html